config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'courses/show/:id', to: 'courses#show', as: 'course'
  
  get 'students/index'

  get 'students/show'

  root "courses#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :field, presence: true
    has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, :presence => true

  belongs_to :course, required: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    begin
      @course = Course.find(params["id"])      
    rescue ActiveRecord::RecordNotFound => error
      redirect_to '/courses/index'
    rescue NameError => error
      redirect_to '/'
    end
    # @c_students = @course.students # Student.where("course_id = ?",params["id"])
    # @c_students = @c_students.to_a unless @c_students.nil?
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 
  def index 
     @students= Student.all
  end

  def show
    @student = Student.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/index.html.erb
<h1>Courses#show_course</h1>

<% @courses.each do |c|  %>
  <%= link_to c.field,course_path(c) %>
    <br>
<% end %>

app/views/courses/show.html.erb
<h1>Liste des étudiants suivant le cours "<%= @course.field %>"</h1>

<%  @course.students.each do |student|  %>
  <%= student.name %>
  <br>  
<% end %>
<br><br>
<%= Time.now %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Classroom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'  %>
  </head>

  <body>
    <div class="col-md-6 col-md-offset-3">
        <%= yield %>
    </div>
  </body>
</html>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>
<% @students.each do |student|  %>
  <%= student.name %>

<% end %>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

<%= @student.name %>